server:
  port: 8090

logging:
  path: E:/SpringBoot/log
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: ERROR

mybatis:
  type-aliases-package: com.chenfeng.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    # 使用阿里巴巴druid
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
